name: backend-ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m venv v
          . v/bin/activate
          pip install -r backend/requirements.txt
      - name: Django checks
        run: |
          . v/bin/activate
          python backend/manage.py check
      - name: Placeholder tests (Codex will replace)
        run: |
          . v/bin/activate
          python - <<'PY'
print("No tests yet; Codex will add smoke tests in P1.")
PY
