name: frontend-ci
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Frontend smoke
        run: |
          echo "TODO: add eslint/tsc/vitest"
          echo "frontend ok"
